[theme]
base = "light"
primaryColor = "#00103f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa" 
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true

[client]
# Force light mode
toolbarMode = "minimal"
showSidebarNavigation = true